name: CI

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        run: |
          flutter --version
          flutter doctor -v

      - name: Get dependencies
        run: flutter pub get

      - name: Run tests
        run: ./scripts/ci-test.sh

  build-macos:
    name: Build macOS
    runs-on: self-hosted
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        run: |
          flutter --version
          flutter doctor -v

      - name: Get dependencies
        run: flutter pub get

      - name: Build macOS app
        run: ./scripts/ci-build-macos.sh

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: nhac-macos
          path: build/macos/Build/Products/Release/nhac.app
          retention-days: 7

  build-linux:
    name: Build Linux (Flatpak)
    runs-on: self-hosted
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Linux app in Docker
        run: ./scripts/ci-build-linux.sh

      - name: Upload Linux Flatpak
        uses: actions/upload-artifact@v4
        with:
          name: nhac-linux-flatpak
          path: nhac.flatpak
          retention-days: 7

      - name: Upload Linux binary
        uses: actions/upload-artifact@v4
        with:
          name: nhac-linux-binary
          path: build/linux/x64/release/bundle/
          retention-days: 7

  build-android:
    name: Build Android
    runs-on: self-hosted
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        run: |
          flutter --version
          flutter doctor -v

      - name: Setup Java
        run: |
          echo "JAVA_HOME=/Applications/Android Studio.app/Contents/jbr/Contents/Home" >> $GITHUB_ENV
          export JAVA_HOME="/Applications/Android Studio.app/Contents/jbr/Contents/Home"
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV
          export PATH="$JAVA_HOME/bin:$PATH"
          java -version

      - name: Get dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release

      - name: Build Android App Bundle
        run: flutter build appbundle --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: nhac-android-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7

      - name: Upload App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: nhac-android-bundle
          path: build/app/outputs/bundle/release/app-release.aab
          retention-days: 7

  release:
    name: Create Release
    runs-on: self-hosted
    needs: [build-macos, build-linux, build-android]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            nhac-macos/nhac.app
            nhac-linux-flatpak/nhac.flatpak
            nhac-android-apk/app-release.apk
            nhac-android-bundle/app-release.aab
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}